version: '3'

services:
    web:
        build: .
        container_name: django
        command: >
          sh -c "python3 manage.py migrate &&
                 python manage.py collectstatic --noinput &&
                 gunicorn store.wsgi:application --bind 0.0.0.0:8000"
        volumes:
          - static_volume:/project/static
          - media_volume:/project/media
        expose:
          - 8000
        depends_on:
          - db

    db:
        image: postgres:alpine
        container_name: postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_DB=${DATABASE_NAME}

    nginx:
      build: ./docker/nginx
      container_name: nginx
      volumes:
        - static_volume:/project/static
        - media_volume:/project/media
      ports:
        - "1337:80"
      depends_on:
        - web

    redis:
      image: redis:alpine
      container_name: redis
      expose:
        - 6379

    celery:
      build: .
      restart: always
      command: celery -A store worker -l INFO
      volumes:
        - static_volume:/project/static
        - media_volume:/project/media
      depends_on:
        - db
        - redis
        - web

volumes:
  postgres_data:
  static_volume:
  media_volume: